name: ROS 2 Industrial CI
on:
  pull_request:
  push:
    branches:
      - humble-devel

jobs:
  clang_format_check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run industrial_ci
        uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: humble # Replace humble for your chosen distro.
          CLANG_FORMAT_CHECK: file
          CLANG_FORMAT_VERSION: "14"

  clang_tidy_check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run industrial_ci
        uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: humble # Replace humble for your chosen distro.
          # UPSTREAM_WORKSPACE: dependencies.rosinstall
          # BEFORE_BUILD_TARGET_WORKSPACE: 'apt update -q && python3 -m pip install ****'
          CLANG_TIDY_ARGS: '--extra-arg=-std=c++17'
          CLANG_TIDY: pedantic

  black_check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run industrial_ci
        uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: humble # Replace humble for your chosen distro.
          BLACK_CHECK: true

  pylint_check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run industrial_ci
        uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: humble # Replace humble for your chosen distro.
          # UPSTREAM_WORKSPACE: dependencies.rosinstall
          BEFORE_BUILD_TARGET_WORKSPACE: 'apt update -q && apt install -y python3-tk && python3 -m pip install pillow numpy ruamel.yaml'
          PYLINT_ARGS: '--errors-only'
          PYLINT_CHECK: true

  build_check:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        env:
          - ROS_DISTRO: humble # Replace humble for your chosen distro.
            ROS_REPO: main
            # UPSTREAM_WORKSPACE: dependencies.rosinstall
            # BEFORE_BUILD_TARGET_WORKSPACE: 'apt update -q && python3 -m pip install ****'
            IMMEDIATE_TEST_OUTPUT: true
          - ROS_DISTRO: humble # Replace humble for your chosen distro.
            ROS_REPO: testing
            # UPSTREAM_WORKSPACE: dependencies.rosinstall
            # BEFORE_BUILD_TARGET_WORKSPACE: 'apt update -q && python3 -m pip install ****'
            IMMEDIATE_TEST_OUTPUT: true

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run industrial_ci
        uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
